import React, { useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import MainContainer from "@/components/MainContainer";
import Container from "@/components/Container";
import Title from "@/components/Title";
import Dropdown from "@/components/Dropdown";
import Input from "@/components/Input";
import Button from "@/components/Button";
import Alert from "@/components/Alert";
import { resources } from "../../utils/dummyData";
import { DropdownData } from "../../models";

export default function Home() {
  const router = useRouter();
  const { rid } = router.query;

  const [quantityValue, setQuantityValue] = useState<number>(0);
  const [selectedResource, setSelectedResource] = useState<DropdownData | null>(
    resources.find((resource) => resource.rid === Number(rid)) || null
  );

  const [showAlert, setShowAlert] = useState<boolean>(false);

  const handleInputChange = (newValue: number) => {
    setQuantityValue(newValue);
  };

  const handleSelect = (selectedOption: DropdownData) => {
    setSelectedResource(selectedOption);
  };

  const handleAddData = () => {
    if (selectedResource && quantityValue > 0) {
      router.push(
        `/shingeki/table?rid=${selectedResource.rid}&amount=${quantityValue} `
      );
    } else {
      setShowAlert(true);
      setTimeout(() => {
        setShowAlert(false);
      }, 2000);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer backgroundimage="https://cdn.wallpapersafari.com/50/90/jrzIds.jpg">
        <Container>
          {showAlert && (
            <Alert text="No puedes ingresar un recurso vacío, Eren no lo permite 👀" />
          )}
          <Title text="Healthatom no kyojin" />
          <Input
            value={quantityValue || 0}
            onChange={handleInputChange}
            placeholder="Ingresar cantidad"
            measure={selectedResource?.measure || "gramos"}
          />
          <Dropdown
            options={resources}
            preSelectedOption={selectedResource || null}
            onSelect={handleSelect}
          />

          <Button onClick={handleAddData}>Ingresar</Button>
        </Container>
      </MainContainer>
    </>
  );
}
