import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import MainContainer from "@/components/MainContainer";
import Container from "@/components/Container";
import Title from "@/components/Title";
import Dropdown from "@/components/Dropdown";
import Input from "@/components/Input";
import Table from "@/components/Table";
import Button from "@/components/Button";
import Alert from "@/components/Alert";
import { resources } from "../../utils/dummyData";
import { DropdownData, TableData } from "../../models";

export default function Home() {
  const router = useRouter();

  const { rid, amount } = router.query;
  const selectAmount = typeof amount === "string" ? parseInt(amount) : 0;

  const [quantityValue, setQuantityValue] = useState<number>(selectAmount || 0);
  const [selectedResource, setSelectedResource] = useState<DropdownData | null>(
    resources.find((resource) => resource.rid === Number(rid)) || null
  );

  const getTableData = () => {
    const newData: TableData = {
      id: 1,
      resource: selectedResource?.name || "",
      quantity: amount + " " + selectedResource?.measure || "",
      entryDate: new Date().toLocaleDateString(),
    };
    return [newData];
  };

  const [tableData, setTableData] = useState<TableData[]>(getTableData());
  const [showAlert, setShowAlert] = useState<boolean>(false);

  const handleInputChange = (newValue: number) => {
    setQuantityValue(newValue);
  };

  const handleSelect = (selectedOption: DropdownData) => {
    setSelectedResource(selectedOption);
  };

  const handleDeleteRow = (id: number) => {
    setTableData((prevTableData) =>
      prevTableData.filter((row) => row.id !== id)
    );
  };

  const handleAddData = () => {
    if (selectedResource && quantityValue > 0) {
      const newData: TableData = {
        id: tableData.length + 1,
        resource: selectedResource.name,
        quantity: quantityValue + " " + selectedResource?.measure || "",
        entryDate: new Date().toLocaleDateString(),
      };
      setTableData((prevTableData) => [...prevTableData, newData]);

      setQuantityValue(0);
    } else {
      setShowAlert(true);
      setTimeout(() => {
        setShowAlert(false);
      }, 2000);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer backgroundimage="https://cdn.wallpapersafari.com/50/90/jrzIds.jpg">
        <Container>
          {showAlert && (
            <Alert text="No puedes ingresar un recurso vacío, Eren no lo permite 👀" />
          )}
          <Title text="Healthatom no kyojin" />
          <Dropdown
            options={resources}
            preSelectedOption={selectedResource || null}
            onSelect={handleSelect}
          />
          <Input
            value={quantityValue || 0}
            onChange={handleInputChange}
            placeholder="Ingresar cantidad"
            measure={selectedResource?.measure || "gramos"}
          />
          <Button onClick={handleAddData}>Ingresar</Button>
          <Table data={tableData} handleDeleteRow={handleDeleteRow} />
        </Container>
      </MainContainer>
    </>
  );
}
