import React, { useState } from "react";
import Head from "next/head";
import MainContainer from "@/components/MainContainer";
import Container from "@/components/Container";
import Title from "@/components/Title";
import Dropdown from "@/components/Dropdown";
import Input from "@/components/Input";
import Table from "@/components/Table";
import Button from "@/components/Button";
import Alert from "@/components/Alert";
import { resources, originTableData } from "../utils/dummyData";
import { DropdownData, TableData } from "../models";

export default function Home() {
  const [quantityValue, setQuantityValue] = useState<number>();
  const [selectedResource, setSelectedResource] =
    useState<DropdownData | null>();
  const [tableData, setTableData] = useState<TableData[]>(originTableData);
  const [showAlert, setShowAlert] = useState<boolean>(false);

  const handleInputChange = (newValue: number) => {
    setQuantityValue(newValue);
  };

  const handleSelect = (selectedOption: DropdownData) => {
    setSelectedResource(selectedOption);
  };

  const handleIngresar = () => {
    if (selectedResource && quantityValue > 0) {
      const newData: TableData = {
        id: tableData.length + 1,
        resource: selectedResource.name,
        quantity: quantityValue + " " + selectedResource?.measure || "",
        entryDate: new Date().toLocaleDateString(),
      };
      setTableData([...tableData, newData]);
      setSelectedResource(null);
      setQuantityValue(0);
    } else {
      setShowAlert(true);
      setTimeout(() => {
        setShowAlert(false);
      }, 2000);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer backgroundimage="https://cdn.wallpapersafari.com/50/90/jrzIds.jpg">
        <Container>
          {showAlert && (
            <Alert text="No puedes ingresar un recurso vacío, Eren no lo permite 👀" />
          )}
          <Title text="Healthatom no kyojin" />
          <Dropdown options={resources} onSelect={handleSelect} />
          <Input
            value={quantityValue}
            onChange={handleInputChange}
            placeholder="Ingresar cantidad"
            measure={selectedResource?.measure || "gramos"}
          />
          <Button onClick={handleIngresar}>Ingresar</Button>

          <Table data={tableData} />
        </Container>
      </MainContainer>
    </>
  );
}
