import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import MainContainer from "@/components/MainContainer";
import Container from "@/components/Container";
import Title from "@/components/Title";
import Dropdown from "@/components/Dropdown";

import { resources } from "../utils/dummyData";
import { DropdownData } from "../models";

export default function Home() {
  const router = useRouter();

  const handleSelect = (selectedOption: DropdownData) => {
    router.push(`/shingeki/amount?rid=${selectedOption.rid}`);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer backgroundimage="https://cdn.wallpapersafari.com/50/90/jrzIds.jpg">
        <Container>
          <Title text="Healthatom no kyojin" />
          <Dropdown options={resources} onSelect={handleSelect} />
        </Container>
      </MainContainer>
    </>
  );
}
